name: Build and publish API client to branch

on:
  push:
    tags:
      - v*

jobs:
  build_and_publish:
    name: Build and publish API client to branch
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Set env from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Version
        run: echo ${{ env.RELEASE_VERSION }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Generate API client and contracts
        run: npx -y @openapitools/openapi-generator-cli generate -i https://api.nephrolog.lt/swagger/v1/swagger.json -g dart-dio -o api --additional-properties="pubAuthor=Karolis,pubName=nephrolog_api_client,dateLibrary=timemachine,useEnumExtension=true"

      - name: Push generated client to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: ${{ env.RELEASE_VERSION }}
          FOLDER: api
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Auto generated NephroLog API client"

